### ISSUE TITLE
Generate workload YAML from CQL schema file

### ISSUE THREAD

**Issue by grighetto** [datastax/adelphi#86] opened 2021-01-12 16:35 UTC
# Feature Request
### Description

As it stands right now, the NoSQLBench step of the workflow still requires an workload YAML to be provided, that is, it cannot automatically generate the workload from just the CQL schema itself. On the other hand, Gemini already does that for data integrity testing. We want to make NSB be on par with that such that we can do automatic performance testing as well.

### Describe the solution you'd like

Build a tool that takes a CQL schema file and transforms it into the desired output. We'll start with NoSQLBench, but the parsing and transformation pieces could be general enough such that we could reuse it with Harry or Gemini.

### Additional context

┆Issue is synchronized with this [Jira Task](https://datastax-oss.atlassian.net/browse/AD-53) by [Unito](https://www.unito.io)
┆Issue Number: AD-53

**Comment by absurdfarce** [comment] 2021-01-21 17:40
Making some notes for myself here based on some initial analysis

* Requires ability to generate nosqlbench bindings for every underlying CQL type
    * For each type we would want to support sequence and random (based on some distribution) selection
    * Sequence support required for each type for the case where it appears in a primary key
    * Could add some exclusions for particular types...
        * A sequence of inet addresses may make sense logically but might not be something we want to explicitly support
* Next step: analyze table metadata
    * Must generate data for each column included in primary key
    * At least one column in primary key must also support a sequence type (to guarantee uniqueness)
        * Could be chosen at random from collection of primary key columns
        * Could also include a bias towards some types... favor ints if possible, that kind of thing
* Output of this process so far: a collection of tuples
    * Column name
    * Column type
    * nosqlbench binding
* From these inputs we should be able to build the insert/update CQL statements using a template

**Comment by absurdfarce** [comment] 2021-01-22 20:25
A couple additional comments from subsequent analysis.

Base version of nosqlbench config is the version currently used in Adelphi; see https://github.com/datastax/adelphi/blob/2c586b62f0dbe1980a5d48d1f1a2be6649af7825/helm/adelphi/values.yaml#L57-L138.  The default usage within the Adelphi workflow should remove the schema creation blocks (since that will have already been performed earlier in the Argo workflow) and the verification blocks (since we're dealing with performance rather than integrity and we're backstopped by Gemini on integrity anyway).  A base config with these options removed appears to work without issue.

Population of sample data into the tables should fill data for every column for every row written.  The question then becomes what we want to do for the read/write loops in nosqlbench (main-read and main-write in the config).  A number of options were considered here:

* Just select all columns all the time
* Randomly select a subset of columns to select
    * Support random seeding to introduce reproducibiliy
* Select all combinations of all possible subsets of columns
    * Provides widest coverage
        * Goal is to demonstrate a performance change when _some query_ in that set behaves differently between versions
        * Subsequent investigation can isolate the query that's causing a problem
    * Artificially inflates benchmark results
        * Not necessarily a problem as value of nosqlbench results is in comparison to other results rather than absolute representation of performance

Current thinking is that we'll focus on the last option above (query all combinations of subsets of columns) initially.  This will be the default Adelphi will use within it's own workflow.  The "adelphi" tool will be extended to support generating such a config given a connection to a Cassandra instance which already has the target schema installed.  Users who wish to focus on specific queries are encouraged to create their own nosqlbench configs (also using the "adelphi" tool) and remove any undesired queries from that config (docs will be provided to assist with this process).  This process should actually be helped out by the fact that all combinations of column subsets will be included in the generated config; users will be able to see all the possibilities and explicitly select only those they want to keep.

Biggest potential problem that we're aware of so far is that a set of N columns will generate 2**N combinations of column subsets.  For small (i.e. few columns) tables this probably isn't a huge issue but for larger tables this could quickly bog down nosqlbench performance; for a table with 8 columns we'd be doing 256 queries on _every iteration_ of main-read and main-write... and it just gets worse from there.  This is definitely something we'll want to account for.

**Comment by jdonenine** [comment] 2021-01-22 20:36
> Biggest potential problem that we're aware of so far is that a set of N columns will generate 2**N combinations of column subsets. For small (i.e. few columns) tables this probably isn't a huge issue but for larger tables this could quickly bog down nosqlbench performance; for a table with 8 columns we'd be doing 256 queries on every iteration of main-read and main-write... and it just gets worse from there. This is definitely something we'll want to account for.

Perhaps we add a control mechanism to limit the exposure.  Maybe set a maximum limit to the number of queries generated for any single table.  If the user wants to go nuts and run the full set, we could let them, but given that we already have so many questions about the sheer usefulness of the testing, we run with the default sane limit?

**Closed** 2021-08-17 19:17 UTC
Labels: enhancement, hard
